### ISSUE TITLE
chordnames:relaxed transposition issue

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#196] opened 2022-01-03 15:14 UTC
Latest git version 077 seems to default to `chordnames : strict` rather than `relaxed` (as previously?). Briefly confusing, as some undefined chords were output using annotation styling. I'm guessing the `strict` behaviour is to output anything in `[ ]` not recognised as a defined chord using annotation style (seems sensible). Easily adjusted to my usage by putting `chordnames : relaxed` in my config, so only `[*annotations]` with * prefix are output in annotation style, and any other `[chords]` output using chord style.

But, transposition of accidentals causes issues, e.g. `G#` becomes `G#b` with `{transpose: -1}`, and (unsurprisingly) reported as 'unknown chord'
[Test_Annotation.cho.txt](https://github.com/ChordPro/chordpro/files/7802510/Test_Annotation.cho.txt)
[Test_Annotation.cho (ukulele C) git.pdf](https://github.com/ChordPro/chordpro/files/7802511/Test_Annotation.cho.ukulele.C.git.pdf)

No such transposition issue with`chordnames:strict`:
[Test_Annotation.cho (ukulele C) git_strict.pdf](https://github.com/ChordPro/chordpro/files/7802525/Test_Annotation.cho.ukulele.C.git_strict.pdf)

Side observation: `[N.C.]` now outputs empty chord diagrams. I don't think that's happened before for some reason (`auto` is default value of `false`), but does seem to strictly follow principles as my instrument config essentially defines a chord in which all strings are muted:
```
    { "name" : "NC",   "base" : 1,   "frets" :  [ -1,-1,-1,-1 ],   "fingers"  :  [ 0,0,0,0 ],  }, 
    { "name" : "N.C.",   "copy" : "NC" },
```
Is there a way to define a chord like `[N.C.]` in such a way that there's no 'unknown chord' warning, but it doesn't actually generate a diagram?

**Comment by sciurius** [comment] 2022-01-03 16:16
Hmm. I knew NC would be a PITA... I'll look into it.

**Comment by gwyndaf** [comment] 2022-01-03 16:36
Don't know what the coding implications are, but one solution might be an `"omit"` (or `"ignore"` or similar) parameter for instrument configs, or else`"copy" : null` (or similar), e.g. one of
```
{ "name" : "N.C.",   "omit" }
{ "name" : "N.C.",   "copy" : null }
```

**Comment by sciurius** [comment] 2022-01-03 16:51
Yes, I was considering something like that. Can you think of other chords that would be special, similar as NC?

**Comment by sciurius** [comment] 2022-01-03 17:59
Now we have annotations, should NC be treated an annotation? It is not really a chord.

**Comment by gwyndaf** [comment] 2022-01-03 18:38
I've never needed anything other than N.C. or NC, but I'm not the most advanced player/writer. I guess my suggestion allows for other 'chord-like' things that don't need diagrams. Might be a lot of extra work for limited use cases, though.

Philosophically, my thinking is 'chords' are _what_ you play (e.g. G, F#m, or NC to 'play nothing'), while annotations indicate _how_ to play (slowing, a tempo, staccato), so there's a certain logic in NC looking like other chords, even though it's not strictly a chord. I think it's something about the visual cue of `[ ]` (with inline usage) as communicating a sort of 'instrument operation.'

Practically, though, it seems perfectly reasonable (and no extra work) simply to treat [NC] as an annotation that looks a bit like a chord. Square brackets in annotations seem to create understandable nesting issues, but not a big deal to go with (NC) instead.

**Comment by sciurius** [comment] 2022-01-04 11:57
Ok, for the time being I left NC as a chord but ironed out its treatment so it won't get in the way where it should.

**Comment by gwyndaf** [comment] 2022-01-04 19:10
078 seems to work nicely, with no warnings or empty diagrams for NC.

Transposition issues with `{chordnames : relaxed}` seems to have gone, mostly.
Now getting an error in fairly limited circumstances:
```
Can't use an undefined value as an ARRAY reference at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/App/Music/ChordPro/Output/PDF/StringDiagrams.pm line 188.
```
I've cut back a sample song to the lines that cause the issue, which seem to be:
```
{transpose: +10}
[Asus4]
```
Gsus4 exists in my instrument config, and is used in other songs (without transposition) with no error. Using standard instrument configs, same error arises with `guitar.json` (which contains a Gsus4), but not with `guitar-ly.json` (which doesn't, but no 'unknown chord' warning). Interestingly, with no instrument config on command line, there's no error, even though `--verbose` reports `guitar.json` as being used (by default, not from my config).

Error doesn't arise with `{chordnames : strict}`.

Let me know if there's anything I can probe further...

**Comment by sciurius** [comment] 2022-01-05 10:17
I cannot reproduce this. May I ask for a test case?

**Comment by gwyndaf** [comment] 2022-01-05 12:45
Sample song and config file stripped back to the only elements that seem to affect the error message, plus instrument config (though it happens for other instruments, but not all):
[sus4_test.cho.txt](https://github.com/ChordPro/chordpro/files/7814820/sus4_test.cho.txt)
[sus4test.json.txt](https://github.com/ChordPro/chordpro/files/7814822/sus4test.json.txt)
[ukulele_c.json.txt](https://github.com/ChordPro/chordpro/files/7814825/ukulele_c.json.txt)

```
$ chordpro-git --nosysconfig --nouserconfig --config ./sus4test.json  --config ukulele_c sus4_test.cho.txt 
Can't use an undefined value as an ARRAY reference at /media/nfs/Shared/Music/Technology/ChordPro/git/chordpro/script/../lib/App/Music/ChordPro/Output/PDF/StringDiagrams.pm line 188.
```
However, passing the config setting via command line gives no error:
```
$ chordpro-git --nosysconfig --nouserconfig --define settings.chordnames=relaxed --config ukulele_c sus4_test.cho.txt 
```
Also, no error if the `include` line is enabled in sus4test.json (to specify instrument from config, not command line):
```
$ chordpro-git --nosysconfig --nouserconfig --config ./sus4test.json sus4_test.cho.txt
```
So, I think my inferences are:
* Error if `chordnames:relaxed` in config file, but not if passed via command line
* Error if instrument config given on command line, but not if specified via an `include`

I think my instrument config is sound (but attached anyway). Seems like it might be something to do with the order in which configuration settings are processed?

**Comment by gwyndaf** [comment] 2022-01-05 13:38
Tested source song with a few different chords and transposition. Amount of transposition doesn't seem to change error, and it arises with `Asus4`, `Asus`, `Esus4`, `Esus` chords, but other sus/sus4 chords seem ok.

Suggests it might be related to the original chord name, not the post-transpose chord?

Another strange thing: `Asu` warns (expectedly) of an unknown chord, but `As` passes with no error, even though I've no such `As` defined in my instrument config. Same for `Es`. Apparently As and Es are proper note names in Dutch/German notation (Ab and Eb), so I wonder if it's something to do with the first two characters being read and treated as root notes?

**Comment by sciurius** [comment] 2022-01-06 10:07
Yes, that's exactly the problem. A chord named `Axxx` will be seen as `A` + `xxx` while `Asss` will be seen as `As` + `ss`.
If you set `settings.chordnames:relaxed` in your config, then it will be effective when your config (and chords) is processed. When you set it on the command line it may (but should not) affect parsing of built-in chords. There can be delicate interactions.

Do you have a compelling reason to use relaxed chordnames?

**Comment by sciurius** [comment] 2022-01-06 10:08
I've checked in a fix, can you try?

**Comment by gwyndaf** [comment] 2022-01-06 11:41
Nice one: that seems to have fixed it in 079.

I don't have a particular need to use `relaxed` so am now back to `strict`. I tried it as a workaround when NC started displaying with annotation style (even though defined in my instrument config).

Having now seen the beta documentation, I possibly misunderstood the purpose of `chordnames` and it seems unrelated to whether or not a chord is known (i.e. _defined_), simply that it has an understandable (built-in) name, so I think `strict` actually does all I need (as it had been doing previously). None of my chord names are particularly strange, and `strict` seems to accept slash / chords as understandable.

My actual use case is an evolving book of songs, which I generate in versions for ukulele (x3 tunings), guitar, mandolin, keyboard. Some instruments have more extensive instrument configs than others, but I don't mind a few missing diagrams as long as the chordnames look right, for which I think `strict` actually does the job nicely.

**Comment by gwyndaf** [comment] 2022-01-06 12:10
Not sure if it's appropriate to add here, but the same undefined array error arises when processing 
[Transpose_to_missing.cho.txt](https://github.com/ChordPro/chordpro/files/7821535/Transpose_to_missing.cho.txt)
```
$ chordpro-git -X --config guitar Transpose_to_missing.cho.txt 
```
More an accidental discovery than anything that immediately affects my usage, and only with built-in guitar.json not guitar-ly.json.

I think the issue arises when the chord (D9) in the source is recognised, but the resulting chord after transposing (Db9) isn't defined. Clearly best to have comprehensive instrument configs, but just flagging in case it's useful to know about for catching/reporting.

**Comment by sciurius** [comment] 2022-01-06 13:34
Yes, this is exactly what the original problem was. Since it was not very clear under what circumstances it can happen I left the traps in and fixed the cause instead of the symptom.

Pull and try...

**Comment by gwyndaf** [comment] 2022-01-06 17:08
OK, I got some test fails in `make all test` but it still reports as v081, so I'm assuming it's ok.

Undefined array error seems to have gone with that scenario (transposing to undefined chord), and generates expected output.

Some NC cases are still output in annotation (not chord) style (with `strict` chordnames), e.g. using default `mandolin-ly.json`, but easily fixed by creating my own config with NC lines added in.

**Comment by sciurius** [comment] 2022-01-06 17:15
Okay, I'll take a look at the test failures later.

NC has no special meaning, it needs to be defined. It is standard in the guitar configs but not in the ukulele configs. I'll add it.
Since you use your own ukulele config you need to add NC and N.C. there as well.

**Comment by sciurius** [comment] 2022-01-06 20:37
Please pull & check, the make test failures should be gone.

**Comment by gwyndaf** [comment] 2022-01-06 21:24
`make test all` works nicely now (no fails) with 082.

Also I notice that 'unknown chord' warnings have returned, which were absent with 081, but possibly something to do with the tests that failed. They're a handy reminder of any chords I might need to add into instrument configs, or else can ignore.

**Comment by sciurius** [comment] 2022-01-06 21:27
Yes, for this reason I still keep the messages. Maybe I'll remove them at release time (or maybe not).

**Closed** 2022-02-05 19:41 UTC
