### ISSUE TITLE
Improve odd/even page placing of two-page songs

### ISSUE THREAD

**Issue by bublath** [ChordPro/chordpro#246] opened 2022-09-11 10:31 UTC
I'm currently trying to find a way to create a patch, that would add an extended mode for pagealign-songs. I was thinking to e.g. use a value of 2 for that mode.
The idea is to place 2-page songs on even pages (so you don't need to turn the page when playing) while still put 1-page songs on even and odd pages (to save paper).
The "simple" approach would be to just check if the song has 2 pages (for 3 or more pages it does not matter as you anyway need to turn the page) and only add an empty page before, if it starts on an odd page.
My problem: I try to implement this in PDF.pm in generate_songbook() but it looks like generate_song() which needs to be called to know the number of pages already adds the first page, at least when I rearranged the code to get the number of pages first, I got a blank page between the first and second page. @sciurius maybe you have a hint here?

Actually the "premium" solution for me would be another mode (=3 ?) where instead of adding blank pages, it would look for the next 1-page song and move it in front of the 2-page song to avoid "wasting paper" with blank pages.

I realize that I could use "filelist" to achieve what I want for a specific songbook, but I would prefer automation.

**Comment by sciurius** [comment] 2022-09-11 13:46
The pages alignment code is quite hairy and took me a long time to get correct. Caveat emptor!
Basically you're hitting a catch-22 situation. To know whether to start the song on the left or right page, you need to generate the song. Generating the song needs to know whether to start on the left or right page to get the page numbers right. 
Maybe a different approach is possible: Always place on the left (even pages), and when the song is a single page, add an empty page and re-generate the song for the right (odd) page. Hoping regenerating will not have nasty side effects...
Liikewise, your 'premium' solution would require all songs to be generated twice, not something I would look forward to.

The filelist is an excellent tool to deal with andvanced song orderning but there would need to be a means to control, in the filelist, whether songs start on left/right pages.

Most of all I have some doubts whether this would actually worth the efforts. Maybe something to discuss in the user group?

**Comment by bublath** [comment] 2022-09-11 19:42
I played around with generating the page twice, but that creates chaos (headlines with wrong body etc.)
To do this right, we probably would need a "dummy ::Writer" that we can be passed to generate_song the first time to count the pages.

Maybe the idea with letting the user add {pages:2} and {align:even} as directives is the simplest approach. It's at least better than using filelist.

**Comment by sciurius** [comment] 2022-09-12 07:58
See https://groups.io/g/ChordPro/message/1527 .

**Comment by bublath** [comment] 2022-09-13 09:21
I did a quick PoC implementation that I pushed (based on your dev branch) to
https://github.com/bublath/chordpro/commits/pagealignment
It uses the method to first count the pages and then re-arrange, which of course increases processing time. For my version I added a progress indicator in verbose mode to keep me entertained. My test songbook has 91 pages, so it takes a bit.
It uses pagealign-songs=2 to add empty pages and pagealign-songs=3 to rearrange pages.

Some thing I noticed (due to the progress indicator): The one page that uses the {image:} directive takes extremely long, I'd say almost 10s by itself, though the png is just 120k. I wonder if there is potential to improve that.

**Comment by sciurius** [comment] 2022-09-13 09:41
> The one page that uses the {image:} directive takes extremely long, I'd say almost 10s by itself, though the png is just 120k.

Yes, there is currently a problem with scaling PNGs. The problem is known but not yet addressed by upstream maintainers. 
If you convert the image to JPG you'll notice it is much faster.

**Comment by bublath** [comment] 2022-09-13 20:44
jpg works fine without any noticable delay. Thanks for the hint.

Did some further modifications. I experimented using the sort() function instead of rearranging arrays during processing.
This got me the idea to extend things to not only rearrange pages based on the 2-page algorithm, but also to offer sorting them by title or author. Even first sort them by title (to make sure the overall structure is fine) and then apply the 2-page optimization.
Makes it more independant from filenames. Everything is now configured via "sort-pages" which takes a list of keywords.
I even implemented a descending order (mainly for test purposes as this creates a clearly visible different result)

**Closed** 2024-01-11 13:00 UTC
Labels: wontfix
