### ISSUE TITLE
chord `B` in `notes.system:german` is transcoded to `H` in `settings.transcode:german`

### ISSUE THREAD

**Issue by chriswep** [ChordPro/chordpro#233] opened 2022-08-04 09:47 UTC
given the config below, chordpro converts the chord `B` in our source files to `H` in the output (there is no transposing activated, all other chords stay the same). As i understand it, chordpro should interpret `B` as the flat version of `H` if we set `notes.system:german` (and consequently don't change it for output if transcode is set to the same system). Is this a bug or do i misunderstand how it's supposed to work?

```
{
    "settings": {
        "transcode": "german"
    },
     "notes": {
        "system": "german",
        "sharp": [
            ["C"],
            ["Cis", "C#", "C♯"],
            ["D"],
            ["Dis", "D#", "D♯"],
            ["E"],
            ["F"],
            ["Fis", "F#", "F♯"],
            ["G"],
            ["Gis", "G#", "G♯"],
            ["A"],
            ["Ais", "A#", "A♯"],
            ["H"]
        ],
        "flat": [
            ["C"],
            ["Des", "Db", "D♭"],
            ["D"],
            ["Es", "Eb", "Ees", "E♭"],
            ["E"],
            ["F"],
            ["Ges", "Gb", "G♭"],
            ["G"],
            ["As", "Ab", "Aes", "A♭"],
            ["A"],
            ["B"],
            ["H"]
        ]
      }
}
```

**Comment by sciurius** [comment] 2022-08-04 11:46
It is definitely not an intuitive result.

This is more or less what happens. You use a `B` chord. ChordPro knows (because of `--config notes:german`) that this is the chord with root `H`. It looks up chord with root `H` in the defined chords and doesn't find it, the built-in chords are in common notation. It retries by name and now it finds chord `B` with root `B`. Transcoded to german this results in chord `H`. 

So the basic problem is that the built-in chords do not match the chords in german.

Best thing you can do is define your B and H chords in your config.
````
{
    "include" : [ "notes:german" ],
    "chords" : [
	{ "name" : "H", "base" : 1, "frets" : [ 2,2,4,4,4,2 ] },
	{ "name" : "B", "base" : 1, "frets" : [ 1,1,3,3,3,1 ] },
    ],
}
````
Note that you must **not** use transcode settings.

**Comment by chriswep** [comment] 2022-08-04 13:10
> It is definitely not an intuitive result.

but is it intended? to me as a user this feels like a bug. if this is intended: doesn't this effectively mean that when using source files in german notation, neither transposing nor transcoding works? and what is the purpose of the `notes` config then?

Is it correct to say that - as of now - the only way to use transcoding and/or transposing is to use common notation in source files?

> ChordPro knows that this is the chord with root H.
> It retries by name and now it finds chord B with root B.

I don't know the implementation details of chordpro, so i can't speak into how deep this cuts into the architecture of the code. However this sounds and looks like a bug. It shouldn't continues with the root B when it knows it is not. I know as a developer that the reasons behind this are probably more complicated than it seems, however i suggest to at least put this on the roadmap to fix/refactor.

**Comment by AnniePerson** [comment] 2022-08-04 20:30
I'm also German and in my opinion traditional notation with B Fis Ges and lowercase minor chords (btw. usually its em7 not e7) is only used in very traditional environments like classical music or some German traditional folk (to avoid calling it outdated)
For scores that I write myself I use 
Notation: Common
so that my ChordPro files are compatible with many ChordPro programs, not only with the ChordPro reference implementation (I also use Mobile Sheets Pro, SongPress, ABC and MuseScore)
Transcode to: Scandinavian
Because the resulting chords are never misleading for most musicians. I think it is very easy to get used to it. The only downside is that I have to explain H to fellow musicians from other countries.

I use lyrics&chords, chord grids and ABC embedding. I don't use chord diagrams, that might make it a bit easier.

**Comment by chriswep** [comment] 2022-08-22 09:21
@sciurius is this something i should look into finding a workaround for our project or is this something you intend to fix/change (i.e.: supporting transpose when using german notation in source files)?

the workaround i am considering is either convert all source files to common notation (and transcode for output) or do the conversion temporarily (with some regex replacing  B>Bb / H>B) in a script whenever a pdf is generated. the former would lead to confusion with our users that contribute source files. the latter would introduce unwanted complexity and dependencies into the project. 

maybe it would be a reasonable solution if a german > common conversion would be done internally by chordpro before processing german files with transcode enabled (or more specific: a special pre-processing of H and B chords)? It feels like this is what should happen anyway when transcoding but then again i don't fully understand the internals why this issue exists.

**Comment by sciurius** [comment] 2022-08-22 11:50
IIRC the problem is not parsing and transposing/transcoding songs wrtten in german notation. That works.
The problem is that you want german chords, and these do not exist. Worse, the built-in common chords confuse the parser when it tries to understand the chords as german.
I agree that this is not intuitive and should be addressed in a future version.
In the mean time there are some options.
First, and preferred, option is to write songs in common notation and transcode to german. This has a lot of advantages, like being able to use the already existing built-in chords, and being able to share songs with othr, non-german people.
Another option is to provide a set of chords in german notation (you're lucky, you only need to provide the B and H chords since the others match common notation).
If you want to try regex replacing, please look for "preprocessor" in ChordPro/Config.pm and the Hints in the docs.

Sorry for the inconvenience, I hope this will get you on the way.

**Closed** 2023-01-28 17:17 UTC
