### ISSUE TITLE
Warning "Invalid -style for page labels; defaulting to decimal...  

### ISSUE THREAD

**Issue by topchyan** [ChordPro/chordpro#197] opened 2022-01-04 01:21 UTC
## Describe the bug
Every chordpro use, regardless of configs, produces this warning
`Invalid -style for page labels; defaulting to decimal at /usr/local/share/perl/5.30.0/App/Music/ChordPro/Output/PDF/Writer.pm line 384.`

### To Reproduce
1. Run `chordpro "any_song.pro"  `

-->

## System information
 - OS: Linux Mint 20.2 (Ubuntu based)
 - Chordpro installed from CPAN using CPAN::Minus

```
Run-time information:
  ChordPro core          5.985
  Perl                   v5.30.0 (/usr/bin/perl)
  CHORDPRO_LIB           /home/avetik/.config/chordpro
  Resource path          /home/avetik/.config/chordpro
                         /usr/local/share/perl/5.30.0/App/Music/ChordPro/res

Modules and libraries:
  Storable               3.15
  Text::Layout           0.027
  File::LoadLines        1.021
  PDF::API2              2.043
  Font::TTF              1.06

```

**Comment by sciurius** [comment] 2022-01-04 07:00
This is a warning given by newer versions (as of 2.043) of the PDF::API2 library. It is caused by a small incompatibility in the call to setup the format for page labels. ToC pages are numbered i, ii, iii and so on; song pages are numbered 1, 2, 3 and so on. The way this is set up changed slightly in 2.042.

It was an error in 2.042, the PDF::API2 maintainer kindly fixed it for ChordPro in 2.043 but kept a warning.

There's a fix in the development version in git that will be part of the next release.

**Closed** 2022-02-05 19:40 UTC
