### ISSUE TITLE
ABC testing observations/issues

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#329] opened 2023-12-05 16:46 UTC
I've been testing out recent updates with ABC score, in actual songs and test samples. Initially with _049 (first embedded ABC), and now update _051.

__1. Scaling (general) - observations__
A few scaling principles seem to have changed in _049 from previously, so scores in some songs came out at different sizes to previously, but a simple `scale` tweak restored the earlier sizes. _051 seems to have introduced slightly different scaling principles to _049, so I need to tweak again to achieve consistent sizes. Not really an issue, as I'm sure this will stabilise.

Many short score snippets now look tidier, with no stretching. I guess this is from addition of `%%stretchlast 0` to the preamble, assuming that a one- or two-bar score is treated as a 'last line'.

__2. Last line scaling - issue__
There's an odd issue with the last line being _scaled down_ (i.e. _not_ condensed) to match the width of the previous lines. That's happening in 051, but doesn't arise with release version (or separate test with qABC/abc2ps):
[abc_test_0xx.cho.txt](https://github.com/ChordPro/chordpro/files/13562710/abc_test_0xx.cho.txt)
[abc_test_051.pdf](https://github.com/ChordPro/chordpro/files/13562713/abc_test_051.pdf)
[abc_test_release.pdf](https://github.com/ChordPro/chordpro/files/13562714/abc_test_release.pdf)
It's an odd case because the source 'medium score' has manual line breaks in the first two source lines, then a long line. I know ABC automatically wraps the output of long source lines. Maybe, if some lines already have manual breaks, ABC assumes all line breaks are under manual control.

However, I'd expect the long source line either to be wrapped automatically (as with 'long' version), or to have the _note_ spacing condensed, but not the whole staff scaled down, which looks odd. This seems like an ABC issue, though, so perhaps outside ChordPro control.

__3. Missing label - user issue?__
If scores are labelled using `{start_of_abc: Score label}`, I now find the label isn't output. This works as expected processing with no config `-X`, but seems to arise with my own config. I'm sure there's something suspect in my configs, but it's a recent issue and I can't think of anything relevant that I've changed.

Using the sample source above, with my own config:
[abc_test_0xx (guitar) git_051.pdf](https://github.com/ChordPro/chordpro/files/13563214/abc_test_0xx.guitar.git_051.pdf)

I'll continue digging into this one, to see if I can narrow down the exact circumstances that trigger it.

**Comment by sciurius** [comment] 2023-12-05 18:51
Oh, I love your testing!

First a remark: abc2svg is under very active development and many recent changes have impact on how a score renders within ChordPro. Several of these changes were on my request, to get better SVG images. Unfortunately abc2svg doesn't carry useful version information so changes in rendering are hard to identify. That is one of the reasons I'm advocating the `JavaSctipt::QuickJS` module, since that allows ChordPro to fully control what abc2svg source/version is used.

BTW Did you ever try the dockers? https://hub.docker.com/repository/docker/chordpro/chordpro (released) and https://hub.docker.com/repository/docker/chordpro/chordpro-dev (development).

Let's look at the results.
The first line is just a single line. This is the starting point.

Line 2, 75% ChordPro scaling, looks ok to me.

Line 3, 75% ABC scaling seems to do nothing but that is coincidental. 75% is the default scaling (pixels/point).
With `%%pagescale 0.75` you get the desired scaling. See http://moinejf.free.fr/abcm2ps-doc/scale.xhtml.

_To be continued later..._

**Comment by gwyndaf** [comment] 2023-12-05 19:58
Thanks for the documentation link, which is extremely useful. I was using the official(?) standard at abcnotation.com, but it seems to only list the directives, with give no guidance on their usage.

My main use for `%%scale` isn't actually to scale the final output, but (by trial and error) it can help fit a score to, for instance, two lines instead of three, in a few cases. I'll then also use ChordPro scaling to ensure all scores are of comparable scale (e.g. clef size) across all songs.

Aside from `%%pagescale` superseding `%%scale` as you mention, I now see that directives like `%%maxshrink` and `%%breaklimit` might actually be a more proper way of controlling line breaks and fitting scores, so I'll need to try using those.

I know nothing of Docker, but this might be a good reason to explore it :)

**Comment by sciurius** [comment] 2023-12-05 20:24
Line 4 is interesting. If I ask abc2svg to render this at 515px width, I get two lines of 515px and the final line is 734px -- too long. Since it is longer than the page width ChordPro scales it to fit.
I'm inclined to think abc2svg should never produce lines wider than the pagewidth, so this is an abc2svg issue.
When you keep the lines of the score together (by adding `split=0` as the first line) the three lines are scaled to the same amount.

(I'm not really lookling at the output of the release version, since that has too many bugs.)

The last line looks okay.

**Comment by sciurius** [comment] 2023-12-05 21:21
I can reproduce the missing label issue but I don't have a clue yet. More tomorrow...

**Comment by gwyndaf** [comment] 2023-12-05 21:39
OK, it sounds like `split=1` treats each line of ABC output as a separate image. I can see that being useful for long scores, which might need to run over to a new page.

I'd assumed that each ABC score was a single image, as (I think) previously, which I guess is what `split=0` does.

So, that does at least seem like a rational explanation for the behaviour.

**Comment by gwyndaf** [comment] 2023-12-05 22:32
Real-life example of the 'scaled last line' issue, but the converse: last line is larger. I'm guessing the first three lines are scaled down automatically but, because the last line's shorter, it isn't.
![Screenshot from 2023-12-05 22-24-27](https://github.com/ChordPro/chordpro/assets/1415754/b238d171-97af-4404-b6c6-1d299112b7c1)

As you suggest, I can make scaling consistent by using `split=0`, but this seems a more typical/normal case than my testing sample.

**Comment by sciurius** [comment] 2023-12-06 06:33
The last line should never be longer than the page size (and therefore be scaled down) and shorter last lines must be scaled the same as the other lines. In other words, split=0 or split=1 should have no visual differences when the image fits on the page.

Can you pass the abc source? There are some fine-tuning issues with
````
%%stretchstaff 1
%%stretchlast 0
%%trimsvg 1
````
that `abc2svg` is struggling with so I want to pass this to Jean-François.

**Comment by gwyndaf** [comment] 2023-12-06 09:55
Here's the abc source:
```
X:1
K:D
M:4/4
L:1/16
"Em7"ee2e e2ee- eee2 e2e2 | "Asus4"ee2e e2ee- "A"eee2 f2g2 | 
"Em7"ee2e e2ee- eee2 dBd2 | "Asus4"c4 A4 "A"G4 A4 |
"Em7"ee2e e2ee- eee2 e2e2 | "Asus4"de2e e2ee- "A"eee2 f2g2 | 
"Em7"f2e2 d2B2- B2A2 B4 | "Asus4"c4 c4 "A"z8   |
```

Just to confirm how it looks with `split=0`:
![Screenshot from 2023-12-06 09-40-56](https://github.com/ChordPro/chordpro/assets/1415754/da5b369d-daf9-4f42-a6ef-a3f81348a968)


Here's a converse real-life example, equivalent of the 'scaled last line' in the test sample:
![Screenshot from 2023-12-06 09-50-39](https://github.com/ChordPro/chordpro/assets/1415754/63fbd8d6-28c3-4d84-9444-2f69f9c2342a)
From source:
```
split=0
%%maxshrink 0.85
X:1
K:C
M:4/4
L:1/8
"C"[CEG]3 C ED CA, | "F"[CFA]3 F AG FE | "C"[CEG]3 C ED CA, | "F"[CFA]3 F AG FE | "C"[CEG]3 C ED CA, | 
"F"[CFA]3 F AG FE | "F"[CFA]4 F2 G2 | "Ab"[C_E_A]8 | "Ab"[C_E_A]4 _A/2_A/2G F_E | "C"[CEG]4 z G, E2 C2 |
```
With `split=1`, both lines are the same length, but second line is scaled down (same behaviour as test sample):
![Screenshot from 2023-12-06 09-52-45](https://github.com/ChordPro/chordpro/assets/1415754/02d94e43-2fef-417e-bbc5-bba615cdf375)

**Comment by sciurius** [comment] 2023-12-06 09:55
Solved the missing labels mystery ☺.

In your config, you have (shortened):
````
{  "pdf" : {
      "labels" : {
         "align" : "left",
         "comment" : "comment",
         "width" : "auto"
       }
   }
}
````
Setting `comment` to `'comment"` means that section labels must not be printed in the margin, but as comments preceding the section. This functionality was not yet adapted for delegate images,

6.030_054 should do this ok.

**Comment by gwyndaf** [comment] 2023-12-06 10:09
Excellent. Can confirm my comment-styled abc labels have returned with _054 :)

**Comment by sciurius** [comment] 2023-12-06 10:21
> Here's the abc source:

Looks okay in _055. Do you have the right `abc2svg` (see `chordpro --about`)?

**Comment by gwyndaf** [comment] 2023-12-06 12:16
Just updated to _055 and `chordpro --about` now gives me:
```
Run-time information:
  ChordPro core          6.030_055  (Unsupported development snapshot)
  Perl                   v5.36.0    (/usr/bin/perl)
  Resource path          ~/.config/chordpro
                         /media/data2/Shared/Music/Technology/ChordPro/git/chordpro/lib/ChordPro/res
  ABC support            QuickJS_XS (ABC2SVG version 6a97925c43 of 2023-12-02)

Modules and libraries:
  Storable               3.26      
  Object::Pad            0.79      
  Text::Layout           0.032     
  File::LoadLines        1.040     
  PDF::API2              2.044     
  SVGPDF                 0.080     
  Font::TTF              1.06      
  JavaScript::QuickJS    0.18  
```
I seem to have the embedded `abc2svg` files in `lib/ChordPro/res/abc/abc2svg` and the most recent is is `abc2svg-1.js` (6 Dec 23 10:01).

I still have external `abc2svg` installed for compatibility with release version. Might it remove ambiguity if I uninstall that?

Behaviour seems unchanged with _055, i.e. last line still scales differently to preceding lines with `split=1`, and consistently with `split=0`.

**Comment by sciurius** [comment] 2023-12-06 12:38
If you are using the QuickJS_XS builtin version then external files do not matter.

There are two examples in your message. The first has a shorter last line, and the second has a longer last line.

The first example looks fine AFAICS. See [ex1.zip](https://github.com/ChordPro/chordpro/files/13582910/ex1.zip).

The second example I think is a bug in abc2avg, I've reported it. We need to wait for a bugfix from Jean-François.

**Comment by gwyndaf** [comment] 2023-12-06 13:23
Sorry, the 'misbehaviour' of shorter (and scaled up) last line is the image in my [previous message](https://github.com/ChordPro/chordpro/issues/329#issuecomment-1841733632).

I think the cause is chord diagrams on the right, where the abc score is automatically scaled down to the width of the song body area, but last line doesn't seem to follow that same scaling.

If I add a couple of chords in the body of your `ex1.cho` sample and run `chordpro-git -X --config keyboard --def pdf.kbdiagrams.show=right ex1.cho ` I get the last line scaling differently from the others.

**Comment by sciurius** [comment] 2023-12-06 14:21
Ah! I see. I'll investigate.

**Comment by gwyndaf** [comment] 2023-12-06 21:38
BTW, memory/slowdown issues now seem to have gone (as of _055, but possibly earlier). For a book of 150+ songs, memory usage seems to peak at ~1GB with no ill effects on system.

**Comment by sciurius** [comment] 2023-12-06 22:49
Great. How big is the resulting PDF?

**Comment by gwyndaf** [comment] 2023-12-07 08:13
Sorry, I deleted original post because I realised my production script was running the release version!

Now (more awake), _dev_ version _056 is indeed using less memory, which peaks at ~1.5GB. PDF sizes are _very_ slightly increased, e.g. 3.4MB against 3.3MB previously. However, I've also added one or two songs and edits, so I think any change in PDF size can be regarded as negligible.

**Comment by sciurius** [comment] 2023-12-09 15:09
According to Jean-François the problem with the longer (and thus shrinking) last line should be fixed.
Can you try 6.030_057?

**Comment by gwyndaf** [comment] 2023-12-09 19:52
Excellent. First glance, using test sample, looks good, but I'll run some real-life cases as further tests.

**Comment by gwyndaf** [comment] 2023-12-09 22:33
Long last lines now seem to be as expected: scaled consistently with preceding lines, and all the same overall width.

Short last lines continue to be shorter than preceding (as expected). I notice some are now slightly shorter than previously, because note spacing is more consistent with preceding lines. That seems better visually than previous behaviour.

However, with short _single_ lines, note spacing has become much more compressed. Most of my score snippets are just short riffs, so this affects several instances. For example...
Before (_056)
![Screenshot from 2023-12-09 21-42-00](https://github.com/ChordPro/chordpro/assets/1415754/8ded09e1-a82f-4717-9145-ff80aba028d8)
After (_057)
![Screenshot from 2023-12-09 21-42-31](https://github.com/ChordPro/chordpro/assets/1415754/7b9ed533-6da7-4b76-bdfd-fbb360d69cb9)
from the same source of:
```
{transpose: +10}
{start_of_abc-keyboard}
scale=0.75
X:1
K:Bm octave=-1
M:6/8
L:1/8
"Bm"z2 B df"Bm7"a/2f/2 |: "D"a6 | "Bm"f4 B df"Bm7"a/2f/2 :| "D"a6 | "Bm"f6 |

{end_of_abc}
```
Aside from tweaking `%%maxshrink` (laborious trial and error), `%%singleline 1` seems to restore reasonable/readable note spacing for single short lines (as well as compacting long scores to fit one line).

That seems more like a workaround, though. I can't imagine there's a good reason for such tight note spacing on a short line, so that might be a remaining issue.

**Closed** 2024-01-11 10:23 UTC
