### ISSUE TITLE
Fatal problems found when debug is On

### ISSUE THREAD

**Issue by lagtac** [ChordPro/chordpro#312] opened 2023-09-15 14:45 UTC
## Describe the bug

When I enable debug info in PDF, from the help menu, a Fatal Error dialog is displayed.

The debug trace is the following:

 : ChordPro invoked: --nodefaultconfigs --config modern1 --config C:\Users\me\OneDrive\Documents\my\chordpro_config\myconfig.json --transcode common --output C:\Users\me\AppData\Local\Temp\iWYs69D41M.pdf --generate PDF C:\Users\me\AppData\Local\Temp\iWYs69D41M.cho
 : RSC1: C:\Users\me\\.config\chordpro/config/guitar.json
 : RSC3: config/guitar.json
 : RSC1: C:\Users\me\\.config\chordpro/config/guitar.json
 : RSC3: config/guitar.json
 : RSC1: C:\Users\me\\.config\chordpro/fonts/
 : RSC3: fonts/
 : Too few arguments for subroutine 'ChordPro::Config::config_final' at C:/Program Files (x86)/ChordPro.ORG/ChordPro/script/../lib/ChordPro/Output/PDF/Writer.pm line 731.
 : Fatal problems found!

## System information
 - OS: Windows 11
 - Where did you get ChordPro from? Github stable release

 - ChordPro version: 6.0.20
 - Perl version: 5.30.2

## Additional context

I use a custom configuration file. But this also happens with the default settings.
I suspect the program tries to copy configuration files over to user path and it fails. The ~/.config path is empty.

**Comment by sciurius** [comment] 2023-09-15 15:07
Duplicate of #308.

**Closed by sciurius** 2023-09-15 15:07 UTC
