### ISSUE TITLE
transposition bug with: `Asus` and `Esus`

### ISSUE THREAD

**Issue by davemo** [ChordPro/chordpro#48] opened 2018-07-05 14:21 UTC
I seem to have hit a weird edge case on transposition for `Asus` and `Esus`, included below are two examples; hopefully I've provided enough information -- please let me know if I've done something wrong with the syntax as well, I'm fairly new to using ChordPro :)

# `Asus` transposes to `D#us` with an original key of `C`, transposed 7 half steps to `G`

## chordpro syntax
```chordpro
{title: Chainbreaker}
{composer: Jonathan Smith, Mia Fieldes, Zach Williams}
{tempo: 78}
{time: 4/4}
{transpose: 7}
{key: C}

{start_of_verse: Verse 1}
If you've been [C]walking the same old road for [F/C]miles and [C]miles
If you've been [Am7]hearing the same old voice tell the [Asus]same old [Am7]lies
If you're [G]trying to fill the same old [Gsus]holes in-[G]side
There's a better [F]life [F2(no3)] there's a better [Gsus]life [G]
{end_of_verse: Verse 1}
```

## cli execution
`chordpro --config=modern3 chainbreaker.chordpro -o=chainbreaker.pdf`

## pdf output
<img width="692" alt="screen shot 2018-07-05 at 10 11 05 am" src="https://user-images.githubusercontent.com/69559/42328263-cbdb153e-803b-11e8-810b-26a9e6db0b38.png">

## expected output
I would expect `Asus` to be transposed to `Esus` when moving 7 half steps up.

# `Esus` transposes to `C#us` with an original key of `A`, transposed 10 half steps to `G`

## chordpro syntax
```chordpro
{title: Great Are You Lord}
{composer: David Leonard, Jason Ingram, Leslie Jordan}
{tempo: 72}
{time: 6/8}
{transpose: 10}
{key: A}

{start_of_verse: Intro}
[D /][F#m7 /][Esus / //]
{ci: acoustic or piano intro}
{end_of_verse: Intro}
```

## cli execution
`chordpro --config=modern3 great-are-you-lord.chordpro -o=great-are-you-lord.pdf`

## pdf output
<img width="360" alt="screen shot 2018-07-05 at 10 17 50 am" src="https://user-images.githubusercontent.com/69559/42328615-ba703a76-803c-11e8-876b-784ccf8fdf15.png">

## expected output
I would expect `Esus` to be transposed to `Dsus` when moving 10 half steps up.

**Comment by davemo** [comment] 2018-07-05 14:43
If it's helpful, I cloned and added a test that exercises these bugs.

```perl
#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use Test::More tests => 3;

use App::Music::ChordPro::Config;
use App::Music::ChordPro::Songbook;

our $config = App::Music::ChordPro::Config::configurator;
my $s = App::Music::ChordPro::Songbook->new;

my $data = <<EOD;
{title: Swing Low Sweet Chariot}
{key: C}
I [C]looked over Jordan, and [Asus]what did I [C]see,
EOD

eval { $s->parsefile( \$data, { transpose => 7 } ) } or diag("$@");

ok( scalar( @{ $s->{songs} } ) == 1, "One song" );
isa_ok( $s->{songs}->[0], 'App::Music::ChordPro::Song', "It's a song" );

my $song = {
	    'settings' => {},
	    'meta' => {
		       'key' => [ 'G' ],
		       'title' => [
				   'Swing Low Sweet Chariot'
				  ],
		      },
	    'title' => 'Swing Low Sweet Chariot',
	    'chords' => {
			 'origin' => 'song',
			 'type' => 'diagrams',
			 'show' => 'all',
			 'chords' => [
				      'G',
				      'Esus'
				     ]
			},
	    'body' => [
                       {
			 'context' => '',
			 'phrases' => [
					'I ',
					'looked over Jordan, and ',
					'what did I ',
					'see,'
				      ],
			 'chords' => [
				       '',
				       'G',
				       'Esus',
				       'G'
				     ],
			 'type' => 'songline'
		       }
		      ],
	    'source' => { file => "__STRING__", line => 1 },
	    'structure' => 'linear',
	   };

is_deeply( { %{ $s->{songs}->[0] } }, $song, "Song contents" );
```

```shell
t/175_transpose.t ... 1/3 
#   Failed test 'Song contents'
#   at t/175_transpose.t line 65.
#     Structures begin differing at:
#          $got->{chords}{chords}[1] = 'D#us'
#     $expected->{chords}{chords}[1] = 'Esus'
# Looks like you failed 1 test of 3.
```

**Comment by davemo** [comment] 2018-07-05 14:54
Here's the other test which exercises A -> G with `Esus` which should transpose to `Dsus`

```perl
#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use Test::More tests => 3;

use App::Music::ChordPro::Config;
use App::Music::ChordPro::Songbook;

our $config = App::Music::ChordPro::Config::configurator;
my $s = App::Music::ChordPro::Songbook->new;

my $data = <<EOD;
{title: Swing Low Sweet Chariot}
{key: A}
I [A]looked over Jordan, and [Esus]what did I [A]see,
EOD

eval { $s->parsefile( \$data, { transpose => 10 } ) } or diag("$@");

ok( scalar( @{ $s->{songs} } ) == 1, "One song" );
isa_ok( $s->{songs}->[0], 'App::Music::ChordPro::Song', "It's a song" );

my $song = {
	    'settings' => {},
	    'meta' => {
		       'key' => [ 'G' ],
		       'title' => [
				   'Swing Low Sweet Chariot'
				  ],
		      },
	    'title' => 'Swing Low Sweet Chariot',
	    'chords' => {
			 'origin' => 'song',
			 'type' => 'diagrams',
			 'show' => 'all',
			 'chords' => [
				      'G',
				      'Dsus'
				     ]
			},
	    'body' => [
                       {
			 'context' => '',
			 'phrases' => [
					'I ',
					'looked over Jordan, and ',
					'what did I ',
					'see,'
				      ],
			 'chords' => [
				       '',
				       'G',
				       'Dsus',
				       'G'
				     ],
			 'type' => 'songline'
		       }
		      ],
	    'source' => { file => "__STRING__", line => 1 },
	    'structure' => 'linear',
	   };

is_deeply( { %{ $s->{songs}->[0] } }, $song, "Song contents" );
```
```shell
t/175_transpose.t ... 1/3 
#   Failed test 'Song contents'
#   at t/175_transpose.t line 65.
#     Structures begin differing at:
#          $got->{chords}{chords}[1] = 'C#us'
#     $expected->{chords}{chords}[1] = 'Dsus'
# Looks like you failed 1 test of 3.
```

**Comment by sciurius** [comment] 2018-07-05 17:48
Good catch.

The problem is that Asus is parsed as As-us, not A-sus.
Likewise Esus.

This needs fixing.

**Comment by davemo** [comment] 2018-07-05 17:50
Glad to know it's a legitimate bug! I'd be happy to help but my perl is a bit rusty and so I wasn't sure which part of the codebase to dive into for fixing this (i did clone the repo and was able to get a makefile generated to run tests). I'm assuming this is based on logic within `Chords.pm` and the `transpose` method?

**Comment by davemo** [comment] 2018-07-05 17:52
I was also wondering if there would be an easier way to isolation test the `transpose` method to add some more tests for these types of edge-cases. Right now I think the only validation is at the integration test level within the `17x_tranpsose.t` test files, but they all use a base case of the key of `D` and the Swing Low song example.

**Comment by sciurius** [comment] 2018-07-05 19:00
The problem is that there is no clear distinction between edge-cases and
rubbish. The chord suffix can be arbitrarily complex and each time you
think you've got them all someone comes up with yet a new one.

To fix the transposing problem, change Chords.pm, around line 790:

				    A(?:is|\#|s|b)? |
				    E(?:s|b)? |

must be:
				    A(?:is|\#|s(?!us)|b)? |
				    E(?:s(?!us)|b)? |

I'll make some improvements next week.

**Comment by davemo** [comment] 2018-07-05 19:08
Thanks!

**Comment by sciurius** [comment] 2018-07-06 11:32
The fix is in dev and will be part of the next release.

**Comment by davemo** [comment] 2018-07-06 12:43
Thank you for your help on this @sciurius ✨

**Closed** 2018-07-08 11:07 UTC
